# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd9700e0cf7bd475bf2e7b0061a51cb7b4e37d48980535eb35d17a8d96a821212308c0ee9d79c0677491a966a33242764ff2acd20cc290589c3ccc5e3815fbf7

test:
  secret_key_base: 1dfdb1d0390badf5dbe342c6ca41d7800c71dba3930dcc942edb06a9a7d0c1d7497af7275aeac6bd000cd7cba1beb650f4e5fd96c8eeb6c016b4acb4f8336a17

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
